export const LOADING_IN_PROGRESS = "LOADING_IN_PROGRESS";
export const LOADING_ERROR = "LOADING_ERROR";
export const LOADING_SUCCESS = "LOADING_SUCCESS";
export const CLEAR_NEWS = "CLEAR_NEWS";
export const UPDATE_NEWS = "UPDATE_NEWS";
export const CHANGE_TAB = "CHANGE_TAB";
